## Токен от вашего Discord бота
# Чтобы Discord понимал какой бот с ним общается
BOT_TOKEN = "BOT TOKEN HERE"

## ID хозяина Шиори
# У хозяина есть исключительные права на настройку ядра.
# Также на владельца не распространяются ограничения.
BOT_OWNER = [1234]

## Главный сервер Шиори
# На нем будет происходить основное общение с ботом
# Здесь могут работать особые команды или применяться другие бонусы
MAIN_GUILD = 1234

## ID Сервера администраторов
# На этом сервере смогут использоваться команды для настройки Шиори
# На других серверах такие команды будут недоступны
ADMIN_GUILD = 1234

## Режим отладки
# Рекомендуется включить при разработке и отключить в рабочей сборке.
# Отображает больше логов и происходящем в боте.
# Команды будут работать только на сервере администраторов.
#
# Можно включить флагом: --debug
DEBUG = false

## Отладка hikari
# Включает более подробные логи на корневом уровне.
# А также отладку асинхронности.
# Включать только в том случае, если вы знаете что это.
#
# Можно включить флагом: --hikari-debug
HIKARI_DEBUG = false

## Подключение к базе данных
# Бот использует Postgres для хранения изменяющихся данных
# Вы также можете указать путь к сокету, если база работает на локальной машине
DB_DSN = "postgres://user:password@/run/postgresql/chio"
# DB_DSN = "postgresql://user:password@/chio?host=/var/run/postgresql"

## Создавать модели при старте
# При запуске будет выполнен запрос на создание всех таблиц в базе данных.
# В этом есть необходимость только при первом запуске или изменении набора моделей.
#
# Можно включить флагом --create-models
CREATE_MODELS = false

## Синхронизация команд при старте
# При запуске будет отправлен полный список команд Discord, для обновления на серверах.
# Это дорогая операция, потому выполнять её надо при необходимости.
# В этом есть необходимость при первом запуске или обновлении набора расширений.
#
# Можно включить флагом: --sync-commands
SYNC_COMMANDS = false

# Определение путей
# =================

[path]

## Путь к расширением
# Шиори будет искать файлы расширений в указанной директории.
# Файлы, которые начинаются с _ она будет игнорировать.
#
# Можно изменить при запуске флагом: --ext-path
EXTENSIONS_PATH = "extensions/"

## Путь к хранилищу данных бота
# Здесь расширения смогут сохранять свои данные для работы.
# Например фотографии, временные файлы и прочее.
DATA_PATH = "bot_data/"

## Путь к настройкам
# Отсюда бот будет загружать определённые в расширениях настройки.
# Настройки расширений представлены в виде TOML файлов.
CONFIG_PATH = "config/"

# Настройки оформления
# ====================

[custom]

## Отображаемое имя бота
# Используется в представлении и при обращении
name = "Chiori"

## Краткое описание бота
# Пару предложений о том что это за бот.
desc = "Милая горничная для вашего прекрасного сервера."

## Статус бота
# Отображается в профиле бота
# - online.  Используется по умолчанию.
# - idle.    Может устанавливаться автоматически через idle_since.
# - dnd.     Когда хотите показать чтобы бота не трогали ;)
# - offline. может быть полезно при тех. работах.
status = "idle"

# Палитра цветов
# ==============
#
# Используется при стилизации Embed сообщений
# Расширения могут и не использовать палитру цветов
# Цвета описываются в hex формате числа.
[custom.color]

## Основной цвет
# Используется по умолчанию в Embed сообщениях
primary = 0xffcc99

## Вторичный цвет
# Для того чтобы отличать первичное от вторичного
# Может использоваться в пунктах подменю и так далее.
secondary = 0xffcc66

## Приглушённый цвет
# Для не столь важных сообщений.
disabled = 0xff9966

## Акцентный цвет
# Для сообщений, на которых стоит заострить внимание
accent = 0xcc99ff

## Информационный цвет
# Сообщает какие-то подробности или сведения
info = 0x66ccff

## Успешный цвет
# Для выполненных действий
success = 0xccff99

## Предупреждающий цвет
# Это конечно не ошибка, на что-то пошло не так
warning = 0xffcc66

## Ошибка
# ЧТо-то пошло не так и действие не может завершиться
error = 0xff6699

# Активность бота
# ===============
#
# Отображается в профиле и статусе бота.
# Отвечает на вопрос чем занимается бот в данный момент.
[custom.activity]

## Название активности
# Отображается в статусе профиля.
# Например: играет в v0.12.0 ...
name = "v0.13.0 | /chio"

## Состояние
# Может предоставлять дополнительные сведения об активности
# Можно увидеть в профиле, под статусом (названием)
state = "Мило мурлыкаю"

## Ссылка на активность
# Актуально только если активность - транслирует.
# Должна быть ссылкой на Yt/twitch трансляцию.
# url = "https://miroq.ru/chio"

## Тип активности
# 0. Играет
# 1. Транслирует. вы ДОЛЖНЫ указать ссылку на youtube/twitch трансляцию
# 2. Слушает
# 3. Смотрит
# 4. Собственная в формате: <emoji> <name> (Discord не реализовал)
# 5. Соревнуется
type = 0

## Собственные emoji
# Здесь можно перечислить список custom emoji
# Как ключ указывается название - как аргумент идентификатор
[custom.emoji]
