[project]
name = "chiori"
version = "0.13.0"
description = "Multi-functional modular discord bot for fluffy our server"
readme = "README.md"
requires-python = ">=3.12,<4.0"
license = "GPL-3.0-or-later"
dependencies = [
    "aiohttp>=3.14.3",
    "asyncpg>=0.31.0",
    "hikari>=2.6.0",
    "hikari-arc>=2.3.2",
    "hikari-miru>=4.3.1",
    "orjson>=3.12.0",
    "pydantic>=2.13.5",
    "pypika>=0.51.1",
]

[dependency-groups]
dev = [
    "asyncpg-stubs>=0.31.3",
    "nox>=2026.8.17",
    "pyright>=1.1.414",
    "ruff>=0.16.0",
]


[tool.mypy]
ignore_errors = true # I use pyright only because mypy dumb

[tool.pyright]
pythonVersion = "3.12"
typeCheckingMode = "strict"
reportPrivateUsage = false
reportMissingTypeStubs = true
reportUnnecessaryTypeIgnoreComment = "warning"
reportUninitializedInstanceVariable = "error"
